## Import Libaries

In [1]:
%pip install numpy
%pip install pandas
%pip install matplotlib
%pip install seaborn
%pip install plotly

Requirement already satisfied: numpy in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.5.1)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)

Requirement already satisfied: pandas in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)

Requirement already satisfied: matplotlib in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (2.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)

Requirement already satisfied: seaborn in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (2.5.1)
Requirement already satisfied: pandas>=1.2 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)

Requirement already satisfied: plotly in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (7.0.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from plotly) (2.25.0)
Requirement already satisfied: packaging in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from plotly) (26.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## טעינת הקבצים ל Dataframe

In [3]:
categories = pd.read_csv(r"C:\Users\User\Desktop\ספיר\אישי\קורס דאטה אנליסט אנליזה\Northwind project\Northwind Profitability & Growth Analysis using Python\categories.csv")
customers = pd.read_csv(r"C:\Users\User\Desktop\ספיר\אישי\קורס דאטה אנליסט אנליזה\Northwind project\Northwind Profitability & Growth Analysis using Python\customers.csv")
employees = pd.read_csv(r"C:\Users\User\Desktop\ספיר\אישי\קורס דאטה אנליסט אנליזה\Northwind project\Northwind Profitability & Growth Analysis using Python\employees.csv")
order_details = pd.read_csv(r"C:\Users\User\Desktop\ספיר\אישי\קורס דאטה אנליסט אנליזה\Northwind project\Northwind Profitability & Growth Analysis using Python\order_details.csv")
orders = pd.read_csv(r"C:\Users\User\Desktop\ספיר\אישי\קורס דאטה אנליסט אנליזה\Northwind project\Northwind Profitability & Growth Analysis using Python\orders.csv")
products = pd.read_csv(r"C:\Users\User\Desktop\ספיר\אישי\קורס דאטה אנליסט אנליזה\Northwind project\Northwind Profitability & Growth Analysis using Python\products.csv")
suppliers = pd.read_csv(r"C:\Users\User\Desktop\ספיר\אישי\קורס דאטה אנליסט אנליזה\Northwind project\Northwind Profitability & Growth Analysis using Python\suppliers.csv")

print("Categories:", categories.shape)
print("Orders:", orders.shape)

Categories: (8, 4)
Orders: (830, 14)

## תיקון טבלת Categories

In [4]:
categories = categories.rename(columns={
    "CategotyID": "CategoryID",
    "CategotyName": "CategoryName"
})

In [5]:
print(products.head())
print(categories.head())

   ProductID                   ProductName  SupplierID  CategoryID  \
0          1                          Chai           1           1
1          2                         Chang           1           1
2          3                 Aniseed Syrup           1           2
3          4  Chef Anton's Cajun Seasoning           2           2
4          5        Chef Anton's Gumbo Mix           2           2

       QuantityPerUnit  UnitPrice  UnitsInStock  UnitsOnOrder  ReorderLevel  \
0   10 boxes x 20 bags      9.000            39             0            10
1   24 - 12 oz bottles      9.500            17            40            25
2  12 - 550 ml bottles      5.000            13            70            25
3       48 - 6 oz jars     11.000            53             0             0
4             36 boxes     10.675             0             0             0

   Discontinued
0             0
1             0
2             0
3             0
4             1
   CategoryID    CategoryName  \
0           1       Beverages
1           2      Condiments
2           3     Confections
3           4  Dairy Products
4           5  Grains/Cereals

                                         Description  \
0        Soft drinks, coffees, teas, beers, and ales
1  Sweet and savory sauces, relishes, spreads, an...
2                Desserts, candies, and sweet breads
3                                            Cheeses
4                Breads, crackers, pasta, and cereal

                                             Picture
0  0x151C2F00020000000D000E0014002100FFFFFFFF4269...
1  0x151C2F00020000000D000E0014002100FFFFFFFF4269...
2  0x151C2F00020000000D000E0014002100FFFFFFFF4269...
3  0x151C2F00020000000D000E0014002100FFFFFFFF4269...
4  0x151C2F00020000000D000E0014002100FFFFFFFF4269...

## בדיקת נתונים ו EDA

In [6]:
print("Categories:", categories.shape)
print("Customers:", customers.shape)
print("Employees:", employees.shape)
print("Order Details:", order_details.shape)
print("Orders:", orders.shape)
print("Products:", products.shape)
print("Suppliers:", suppliers.shape)

Categories: (8, 4)
Customers: (91, 11)
Employees: (18, 15)
Order Details: (2155, 5)
Orders: (830, 14)
Products: (77, 10)
Suppliers: (29, 12)

In [7]:
dataframes = {
    "Categories": categories,
    "Customers": customers,
    "Employees": employees,
    "Order_Details": order_details,
    "Orders": orders,
    "Products": products,
    "Suppliers": suppliers
}

for name, df in dataframes.items():
    print(f"\n{name}")
    print(df.info())

Categories
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CategoryID    8 non-null      int64
 1   CategoryName  8 non-null      str
 2   Description   8 non-null      str
 3   Picture       8 non-null      str
dtypes: int64(1), str(3)
memory usage: 168.6 KB
None

Customers
<class 'pandas.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    91 non-null     str
 1   CompanyName   91 non-null     str
 2   ContactName   91 non-null     str
 3   ContactTitle  91 non-null     str
 4   Address       91 non-null     str
 5   City          91 non-null     str
 6   Region        31 non-null     str
 7   PostalCode    90 non-null     str
 8   Country       91 non-null     str
 9   Phone         91 non-null     str
 10  Fax           69 non-null     str
dtypes: str(11)
memory usage: 18.1 KB
None

Employees
<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EmployeeID       18 non-null     str
 1   LastName         18 non-null     str
 2   FirstName        17 non-null     str
 3   Title            18 non-null     str
 4   TitleOfCourtesy  9 non-null      str
 5   BirthDate        9 non-null      str
 6   HireDate         9 non-null      str
 7   Address          9 non-null      str
 8   City             9 non-null      str
 9   Region           5 non-null      str
 10  PostalCode       9 non-null      str
 11  Country          9 non-null      str
 12  HomePhone        9 non-null      str
 13  Extension        9 non-null      float64
 14  Photo            9 non-null      str
dtypes: float64(1), str(14)
memory usage: 386.2 KB
None

Order_Details
<class 'pandas.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    2155 non-null   int64
 1   ProductID  2155 non-null   int64
 2   UnitPrice  2155 non-null   float64
 3   Quantity   2155 non-null   int64
 4   Discount   2155 non-null   float64
dtypes: float64(2), int64(3)
memory usage: 84.3 KB
None

Orders
<class 'pandas.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         830 non-null    int64
 1   CustomerID      830 non-null    str
 2   EmployeeID      830 non-null    int64
 3   OrderDate       830 non-null    str
 4   RequiredDate    830 non-null    str
 5   ShippedDate     809 non-null    str
 6   Shipvia         830 non-null    int64
 7   Freight         830 non-null    float64
 8   ShipName        830 non-null    str
 9   ShipAddress     830 non-null    str
 10  ShipCity        830 non-null    str
 11  ShipRegion      323 non-null    str
 12  ShipPostalCode  811 non-null    str
 13  ShipCountry     830 non-null    str
dtypes: float64(1), int64(3), str(10)
memory usage: 165.9 KB
None

Products
<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ProductID        77 non-null     int64
 1   ProductName      77 non-null     str
 2   SupplierID       77 non-null     int64
 3   CategoryID       77 non-null     int64
 4   QuantityPerUnit  77 non-null     str
 5   UnitPrice        77 non-null     float64
 6   UnitsInStock     77 non-null     int64
 7   UnitsOnOrder     77 non-null     int64
 8   ReorderLevel     77 non-null     int64
 9   Discontinued     77 non-null     int64
dtypes: float64(1), int64(7), str(2)
memory usage: 8.5 KB
None

Suppliers
<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SupplierID    29 non-null     int64
 1   CompanyName   29 non-null     str
 2   ContactName   29 non-null     str
 3   ContactTitle  29 non-null     str
 4   Address       29 non-null     str
 5   City          29 non-null     str
 6   Region        9 non-null      str
 7   PostalCode    29 non-null     str
 8   Country       29 non-null     str
 9   Phone         29 non-null     str
 10  Fax           13 non-null     str
 11  HomePage      5 non-null      str
dtypes: int64(1), str(11)
memory usage: 6.3 KB
None

In [8]:
for name, df in dataframes.items():
    print(f"\n{name}")
    print(df.isnull().sum())

Categories
CategoryID      0
CategoryName    0
Description     0
Picture         0
dtype: int64

Customers
CustomerID       0
CompanyName      0
ContactName      0
ContactTitle     0
Address          0
City             0
Region          60
PostalCode       1
Country          0
Phone            0
Fax             22
dtype: int64

Employees
EmployeeID          0
LastName            0
FirstName           1
Title               0
TitleOfCourtesy     9
BirthDate           9
HireDate            9
Address             9
City                9
Region             13
PostalCode          9
Country             9
HomePhone           9
Extension           9
Photo               9
dtype: int64

Order_Details
OrderID      0
ProductID    0
UnitPrice    0
Quantity     0
Discount     0
dtype: int64

Orders
OrderID             0
CustomerID          0
EmployeeID          0
OrderDate           0
RequiredDate        0
ShippedDate        21
Shipvia             0
Freight             0
ShipName            0
ShipAddress         0
ShipCity            0
ShipRegion        507
ShipPostalCode     19
ShipCountry         0
dtype: int64

Products
ProductID          0
ProductName        0
SupplierID         0
CategoryID         0
QuantityPerUnit    0
UnitPrice          0
UnitsInStock       0
UnitsOnOrder       0
ReorderLevel       0
Discontinued       0
dtype: int64

Suppliers
SupplierID       0
CompanyName      0
ContactName      0
ContactTitle     0
Address          0
City             0
Region          20
PostalCode       0
Country          0
Phone            0
Fax             16
HomePage        24
dtype: int64

## בדיקת ערכים חסרים

In [9]:
missing_values = pd.DataFrame({
    "Table": dataframes.keys(),
    "Missing Values": [
        df.isnull().sum().sum()
        for df in dataframes.values()
    ]
})

missing_values

           Table  Missing Values
0     Categories               0
1      Customers              83
2      Employees             104
3  Order_Details               0
4         Orders             547
5       Products               0
6      Suppliers              60

## בדיקת כפילויות

In [10]:
for name, df in dataframes.items():
    print(
        name,
        "duplicates:",
        df.duplicated().sum()
    )

Categories duplicates: 0
Customers duplicates: 0
Employees duplicates: 0
Order_Details duplicates: 0
Orders duplicates: 0
Products duplicates: 0
Suppliers duplicates: 0

## המרת תאריכים

In [11]:
print(orders["OrderDate"].dtype)
print(orders["OrderDate"].head())

orders["OrderDate"] = pd.to_datetime(orders["OrderDate"], dayfirst=True, errors="coerce")
orders["RequiredDate"] = pd.to_datetime(orders["RequiredDate"], dayfirst=True, errors="coerce")
orders["ShippedDate"] = pd.to_datetime(orders["ShippedDate"], dayfirst=True, errors="coerce")
orders["OrderYear"] = orders["OrderDate"].dt.year
orders["OrderMonth"] = orders["OrderDate"].dt.month
orders["OrderMonthName"] = orders["OrderDate"].dt.month_name()
orders["OrderMonthDate"] = orders["OrderDate"].dt.to_period("M")

str
0    04/07/1996
1    05/07/1996
2    08/07/1996
3    08/07/1996
4    09/07/1996
Name: OrderDate, dtype: str

## יצירת חישובי Profitabilty ומטריקות

In [12]:
profitability = orders.merge(
    order_details,
    on="OrderID",
    how="inner"
)
profitability = profitability.merge(
    products,
    on="ProductID",
    how="inner",
    suffixes=("_order", "_product")
)

In [13]:
profitability = profitability.merge(
    categories[["CategoryID", "CategoryName"]],
    on="CategoryID",
    how="left"
)

In [14]:
print(profitability.columns.tolist())
print(categories.columns.tolist())

['OrderID', 'CustomerID', 'EmployeeID', 'OrderDate', 'RequiredDate', 'ShippedDate', 'Shipvia', 'Freight', 'ShipName', 'ShipAddress', 'ShipCity', 'ShipRegion', 'ShipPostalCode', 'ShipCountry', 'OrderYear', 'OrderMonth', 'OrderMonthName', 'OrderMonthDate', 'ProductID', 'UnitPrice_order', 'Quantity', 'Discount', 'ProductName', 'SupplierID', 'CategoryID', 'QuantityPerUnit', 'UnitPrice_product', 'UnitsInStock', 'UnitsOnOrder', 'ReorderLevel', 'Discontinued', 'CategoryName']
['CategoryID', 'CategoryName', 'Description', 'Picture']

In [15]:
profitability.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Shipvia,Freight,ShipName,ShipAddress,...,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice_product,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued,CategoryName
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,...,Queso Cabrales,5,4,1 kg pkg.,10.500,22,30,30,0,Dairy Products
1,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,...,Singaporean Hokkien Fried Mee,20,5,32 - 1 kg pkgs.,7.000,26,0,0,1,Grains/Cereals
2,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,...,Mozzarella di Giovanni,14,4,24 - 200 g pkgs.,17.400,14,0,0,0,Dairy Products
3,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Toms Spezialitהten,Luisenstr. 48,...,Tofu,6,7,40 - 100 g pkgs.,11.625,35,0,0,0,Produce
4,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Toms Spezialitהten,Luisenstr. 48,...,Manjimup Dried Apples,24,7,50 - 300 g pkgs.,26.500,20,0,10,0,Produce

In [16]:
profitability["BuyingCost"] = profitability["UnitPrice_product"]
profitability["SellingPrice"] = profitability["UnitPrice_order"]

profitability["Revenue"] = (
    profitability["Quantity"] *
    profitability["SellingPrice"] *
    (1 - profitability["Discount"])
)

profitability["COGS"] = (
    profitability["Quantity"] *
    profitability["BuyingCost"]
)

profitability["GrossProfit"] = (
    profitability["Revenue"] -
    profitability["COGS"]
)

profitability["GrossMargin"] = np.where(
    profitability["Revenue"] != 0,
    profitability["GrossProfit"] /
    profitability["Revenue"],
    np.nan
)

In [17]:
profitability[
    [
        "OrderID",
        "ProductID",
        "Quantity",
        "BuyingCost",
        "SellingPrice",
        "Revenue",
        "COGS",
        "GrossProfit",
        "GrossMargin"
    ]
].head(10)

,OrderID,ProductID,Quantity,BuyingCost,SellingPrice,Revenue,COGS,GrossProfit,GrossMargin
0,10248,11,12,10.500,14.0,168.00,126.000,42.000,0.250000
1,10248,42,10,7.000,9.8,98.00,70.000,28.000,0.285714
2,10248,72,5,17.400,34.8,174.00,87.000,87.000,0.500000
3,10249,14,9,11.625,18.6,167.40,104.625,62.775,0.375000
4,10249,51,40,26.500,42.4,1696.00,1060.000,636.000,0.375000
5,10250,41,10,4.825,7.7,77.00,48.250,28.750,0.373377
6,10250,51,35,26.500,42.4,1261.40,927.500,333.900,0.264706
7,10250,65,15,10.525,16.8,214.20,157.875,56.325,0.262955
8,10251,22,6,10.500,16.8,95.76,63.000,32.760,0.342105
9,10251,57,15,9.750,15.6,222.30,146.250,76.050,0.342105

## יצירת KPI'S

In [18]:
total_revenue = profitability["Revenue"].sum()

print(f"Total Revenue: ${total_revenue:,.2f}")

total_cogs = profitability["COGS"].sum()

print(f"Total COGS: ${total_cogs:,.2f}")

total_profit = profitability["GrossProfit"].sum()

print(f"Gross Profit: ${total_profit:,.2f}")

gross_margin = (
    total_profit /
    total_revenue
)

print(f"Gross Margin: {gross_margin:.2%}")

Total Revenue: $1,265,793.04
Total COGS: $724,683.66
Gross Profit: $541,109.38
Gross Margin: 42.75%

## Which products and categories generate the highest revenue and gross profit, and which products have weak profitability?

In [19]:
product_profitability = (
    profitability
    .groupby(
        ["ProductID", "ProductName"],
        as_index=False
    )
    .agg(
        UnitsSold=("Quantity", "sum"),
        Revenue=("Revenue", "sum"),
        COGS=("COGS", "sum"),
        GrossProfit=("GrossProfit", "sum")
    )
)

product_profitability["GrossMargin"] = np.where(
    product_profitability["Revenue"] != 0,
    product_profitability["GrossProfit"] /
    product_profitability["Revenue"],
    np.nan
)

product_profitability["ProfitPerUnit"] = np.where(
    product_profitability["UnitsSold"] != 0,
    product_profitability["GrossProfit"] /
    product_profitability["UnitsSold"],
    np.nan
)

## Top 10 Products By GP

In [20]:
top_10_products = (
    product_profitability
    .sort_values(
        "GrossProfit",
        ascending=False
    )
    .head(10)
)

top_10_products

,ProductID,ProductName,UnitsSold,Revenue,COGS,GrossProfit,GrossMargin,ProfitPerUnit
37,38,Cפte de Blaye,623,141396.735,82080.25,59316.485,0.419504,95.211051
28,29,Thringer Rostbratwurst,746,80368.672,46173.67,34195.002,0.425477,45.837804
58,59,Raclette Courdavault,1496,71155.700,41140.00,30015.700,0.421831,20.063971
61,62,Tarte au sucre,1083,47234.970,26695.95,20539.020,0.434827,18.964931
59,60,Camembert Pierrot,1577,46825.480,26809.00,20016.480,0.427470,12.692758
55,56,Gnocchi di nonna Alice,1263,42593.060,23997.00,18596.060,0.436598,14.723721
50,51,Manjimup Dried Apples,886,41819.650,23479.00,18340.650,0.438565,20.700508
16,17,Alice Mutton,978,32698.380,19071.00,13627.380,0.416760,13.933926
17,18,Carnarvon Tigers,539,29171.875,16843.75,12328.125,0.422603,22.872217
27,28,Rצssle Sauerkraut,640,25696.640,14592.00,11104.640,0.432144,17.351000

In [21]:
category_profitability = (
    profitability
    .groupby(
        ["CategoryID", "CategoryName"],
        as_index=False
    )
    .agg(
        UnitsSold=("Quantity", "sum"),
        Revenue=("Revenue", "sum"),
        COGS=("COGS", "sum"),
        GrossProfit=("GrossProfit", "sum")
    )
)

category_profitability["GrossMargin"] = (
    category_profitability["GrossProfit"] /
    category_profitability["Revenue"]
)

## Are the customers generating the highest sales also the customers generating the highest profit?

In [22]:
customer_profitability = (
    profitability
    .groupby("CustomerID", as_index=False)
    .agg(
        Revenue=("Revenue", "sum"),
        COGS=("COGS", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("OrderID", "nunique")
    )
)

In [23]:
customer_profitability["GrossMargin"] = (
    customer_profitability["GrossProfit"] /
    customer_profitability["Revenue"]
)

In [24]:
customer_profitability["AverageOrderValue"] = (
    customer_profitability["Revenue"] /
    customer_profitability["Orders"]
)

customer_profitability["ProfitPerOrder"] = (
    customer_profitability["GrossProfit"] /
    customer_profitability["Orders"]
)

customer_profitability["RevenueRank"] = (
    customer_profitability["Revenue"]
    .rank(
        ascending=False,
        method="dense"
    )
)

customer_profitability["ProfitRank"] = (
    customer_profitability["GrossProfit"]
    .rank(
        ascending=False,
        method="dense"
    )
)

In [25]:
customer_profitability.sort_values(
    "GrossProfit",
    ascending=False
).head(10)

,CustomerID,Revenue,COGS,GrossProfit,Orders,GrossMargin,AverageOrderValue,ProfitPerOrder,RevenueRank,ProfitRank
60,QUICK,110277.3050,61099.870,49177.4350,28,0.445943,3938.475179,1756.336964,1.0,1.0
19,ERNSH,104874.9785,60195.045,44679.9335,30,0.426030,3495.832617,1489.331117,2.0,2.0
68,SAVEA,104361.9500,60359.425,44002.5250,31,0.421634,3366.514516,1419.436290,3.0,3.0
62,RATTC,51097.8005,29281.210,21816.5905,18,0.426958,2838.766694,1212.032806,4.0,4.0
35,HUNGO,49979.9050,30198.955,19780.9500,19,0.395778,2630.521316,1041.102632,5.0,5.0
32,HANAR,32841.3700,17458.300,15383.0700,14,0.468405,2345.812143,1098.790714,6.0,6.0
37,KOENE,30908.3840,16451.310,14457.0740,14,0.467740,2207.741714,1032.648143,7.0,7.0
22,FOLKO,29567.5625,16738.975,12828.5875,19,0.433874,1556.187500,675.188816,8.0,8.0
86,WHITC,27363.6050,15208.800,12154.8050,14,0.444196,1954.543214,868.200357,10.0,9.0
23,FRANK,26656.5595,15897.215,10759.3445,15,0.403628,1777.103967,717.289633,11.0,10.0

## Which high-volume products generate disproportionately low gross profit or gross margin?

In [26]:
volume_margin = product_profitability[
    [
        "ProductID",
        "ProductName",
        "UnitsSold",
        "Revenue",
        "GrossProfit",
        "GrossMargin"
    ]
].copy()

In [27]:
volume_margin["VolumeRank"] = (
    volume_margin["UnitsSold"]
    .rank(ascending=False)
)

volume_margin["MarginRank"] = (
    volume_margin["GrossMargin"]
    .rank(ascending=False)
)

volume_threshold = volume_margin["UnitsSold"].median()
margin_threshold = volume_margin["GrossMargin"].median()

volume_margin["Segment"] = np.select(
    [
        (
            (volume_margin["UnitsSold"] >= volume_threshold) &
            (volume_margin["GrossMargin"] >= margin_threshold)
        ),
        (
            (volume_margin["UnitsSold"] >= volume_threshold) &
            (volume_margin["GrossMargin"] < margin_threshold)
        ),
        (
            (volume_margin["UnitsSold"] < volume_threshold) &
            (volume_margin["GrossMargin"] >= margin_threshold)
        )
    ],
    [
        "High Volume / High Margin",
        "High Volume / Low Margin",
        "Low Volume / High Margin"
    ],
    default="Low Volume / Low Margin"
)

volume_margin[
    volume_margin["Segment"] ==
    "High Volume / Low Margin"
]

,ProductID,ProductName,UnitsSold,Revenue,GrossProfit,GrossMargin,VolumeRank,MarginRank,Segment
0,1,Chai,828,12788.1000,5336.1000,0.417271,20.0,56.0,High Volume / Low Margin
1,2,Chang,1057,16355.9600,6314.4600,0.386065,10.5,74.0,High Volume / Low Margin
10,11,Queso Cabrales,706,12901.7700,5488.7700,0.425428,38.0,45.0,High Volume / Low Margin
15,16,Pavlova,1158,17215.7755,7112.2255,0.413123,5.0,61.0,High Volume / Low Margin
16,17,Alice Mutton,978,32698.3800,13627.3800,0.416760,15.0,57.0,High Volume / Low Margin
25,26,Gumbהr Gummibהrchen,753,19849.1445,8091.0495,0.407627,30.0,65.0,High Volume / Low Margin
28,29,Thringer Rostbratwurst,746,80368.6720,34195.0020,0.425477,31.0,44.0,High Volume / Low Margin
30,31,Gorgonzola Telino,1397,14920.8750,6189.6250,0.414830,3.0,59.0,High Volume / Low Margin
32,33,Geitost,755,1648.1250,704.3750,0.427380,28.5,41.0,High Volume / Low Margin
34,35,Steeleye Stout,883,13644.0000,5697.0000,0.417546,19.0,54.0,High Volume / Low Margin
38,39,Chartreuse verte,793,12294.5400,5157.5400,0.419498,25.0,50.0,High Volume / Low Margin
52,53,Perth Pasties,722,20574.1700,8733.3700,0.424482,36.0,46.0,High Volume / Low Margin
53,54,Tourtiטre,755,4728.2375,1915.8625,0.405196,28.5,66.0,High Volume / Low Margin
54,55,Pגtי chinois,903,17426.4000,6590.4000,0.378185,16.0,75.0,High Volume / Low Margin
58,59,Raclette Courdavault,1496,71155.7000,30015.7000,0.421831,2.0,48.0,High Volume / Low Margin
59,60,Camembert Pierrot,1577,46825.4800,20016.4800,0.427470,1.0,40.0,High Volume / Low Margin
67,68,Scottish Longbreads,799,8714.0000,3720.2500,0.426928,24.0,42.0,High Volume / Low Margin
68,69,Gudbrandsdalsost,714,21942.3600,9090.3600,0.414284,37.0,60.0,High Volume / Low Margin
69,70,Outback Lager,817,10672.6500,4545.1500,0.425869,21.0,43.0,High Volume / Low Margin
70,71,Flotemysost,1057,19551.0250,8188.2750,0.418816,10.5,51.0,High Volume / Low Margin

In [28]:
print(volume_margin)

    ProductID                      ProductName  UnitsSold   Revenue  \
0           1                             Chai        828  12788.10
1           2                            Chang       1057  16355.96
2           3                    Aniseed Syrup        328   3044.00
3           4     Chef Anton's Cajun Seasoning        453   8567.90
4           5           Chef Anton's Gumbo Mix        298   5347.20
..        ...                              ...        ...       ...
72         73                       Rצd Kaviar        293   3997.20
73         74                    Longlife Tofu        297   2432.50
74         75             Rhצnbrהu Klosterbier       1155   8177.49
75         76                     Lakkalikצצri        981  15760.44
76         77  Original Frankfurter grne Soe        791   9171.63

    GrossProfit  GrossMargin  VolumeRank  MarginRank  \
0      5336.100     0.417271        20.0        56.0
1      6314.460     0.386065        10.5        74.0
2      1404.000     0.461235        63.0         8.0
3      3584.900     0.418411        55.0        52.0
4      2166.050     0.405081        67.0        67.0
..          ...          ...         ...         ...
72     1799.700     0.450240        70.0        13.0
73      947.500     0.389517        68.5        73.0
74     3701.865     0.452690         6.0        12.0
75     6931.440     0.439800        13.5        21.0
76     4030.130     0.439413        26.0        23.0

                      Segment
0    High Volume / Low Margin
1    High Volume / Low Margin
2    Low Volume / High Margin
3     Low Volume / Low Margin
4     Low Volume / Low Margin
..                        ...
72   Low Volume / High Margin
73    Low Volume / Low Margin
74  High Volume / High Margin
75  High Volume / High Margin
76  High Volume / High Margin

[77 rows x 9 columns]

## Employee & Geographic Performance

In [29]:
profitability["EmployeeID"] = profitability["EmployeeID"].astype(str)
employees["EmployeeID"] = employees["EmployeeID"].astype(str)

employee_data = profitability.merge(
    employees,
    on="EmployeeID",
    how="left",
    suffixes=("", "_employee")
)

employee_profitability = (
    employee_data
    .groupby(
        ["EmployeeID", "FirstName", "LastName"],
        as_index=False
    )
    .agg(
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("OrderID", "nunique")
    )
)

In [30]:
employee_profitability["GrossMargin"] = (
    employee_profitability["GrossProfit"] /
    employee_profitability["Revenue"]
)

In [31]:
geo_data = profitability.merge(
    customers,
    on="CustomerID",
    how="left"
)

country_profitability = (
    geo_data
    .groupby("Country", as_index=False)
    .agg(
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("OrderID", "nunique"),
        Customers=("CustomerID", "nunique")
    )
)

In [32]:
country_profitability["GrossMargin"] = (
    country_profitability["GrossProfit"] /
    country_profitability["Revenue"]
)

country_profitability.sort_values(
    "GrossProfit",ascending=False
)

        Country      Revenue  GrossProfit  Orders  Customers  GrossMargin
19          USA  245584.6105  105215.4205     122         13     0.428428
8       Germany  230284.6335  101469.2985     122         11     0.440626
1       Austria  128003.8385   53011.2935      40          2     0.414138
3        Brazil  106925.7765   45058.4115      83          9     0.421399
7        France   81358.3225   34553.7425      77         10     0.424711
18           UK   58971.3100   26538.7350      56          7     0.450028
20    Venezuela   56810.6290   23987.0340      46          4     0.422228
16       Sweden   54495.1400   23578.2900      37          2     0.432668
9       Ireland   49979.9050   19780.9500      19          1     0.395778
4        Canada   50196.2900   19246.2150      30          3     0.383419
2       Belgium   33824.8550   14650.3650      19          2     0.433124
17  Switzerland   31692.6590   14419.3840      18          2     0.454976
5       Denmark   32661.0225   13141.4875      18          2     0.402360
11       Mexico   23582.0775   10801.2225      28          5     0.458027
6       Finland   18810.0525    7995.7275      22          2     0.425077
15        Spain   17983.2000    7835.4600      23          4     0.435710
10        Italy   15770.1550    6953.2000      28          3     0.440909
14     Portugal   11472.3625    4465.9125      13          2     0.389276
0     Argentina    8119.1000    3963.6600      16          3     0.488190
12       Norway    5735.1500    2734.9750       6          1     0.476879
13       Poland    3531.9500    1708.6000       7          1     0.483755

## What are the main drivers of changes in Northwind's gross profit over time?

## MoM Growth

In [33]:
profitability["Month"] = (
    profitability["OrderDate"]
    .dt.to_period("M")
)

monthly_profitability = (
    profitability
    .groupby("Month", as_index=False)
    .agg(
        Revenue=("Revenue", "sum"),
        COGS=("COGS", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        UnitsSold=("Quantity", "sum"),
        Orders=("OrderID", "nunique")
    )
)

monthly_profitability["GrossMargin"] = (
    monthly_profitability["GrossProfit"] /
    monthly_profitability["Revenue"]
)

monthly_profitability["RevenueGrowth"] = (
    monthly_profitability["Revenue"]
    .pct_change()
)

monthly_profitability["ProfitGrowth"] = (
    monthly_profitability["GrossProfit"]
    .pct_change()
)

## Profit Concetration

In [34]:
product_profitability = (
    product_profitability
    .sort_values("GrossProfit", ascending=False)
)

product_profitability["ProfitShare"] = (
    product_profitability["GrossProfit"] /
    product_profitability["GrossProfit"].sum()
)

product_profitability["CumulativeProfitShare"] = (
    product_profitability["ProfitShare"].cumsum()
)

products_for_80pct = (
    product_profitability[
        product_profitability["CumulativeProfitShare"] <= 0.80
    ]
    .shape[0]
)

products_for_80pct

35

In [35]:
products_for_80pct

35

## Discount Analysis

In [36]:
profitability["DiscountBand"] = np.select(
    [
        profitability["Discount"] == 0,
        profitability["Discount"] <= 0.05,
        profitability["Discount"] <= 0.10,
        profitability["Discount"] <= 0.20
    ],
    [
        "0%",
        "0-5%",
        "5-10%",
        "10-20%"
    ],
    default="20%+"
)

discount_analysis = (
    profitability
    .groupby("DiscountBand", as_index=False)
    .agg(
        Orders=("OrderID", "nunique"),
        UnitsSold=("Quantity", "sum"),
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum")
    )
)

discount_analysis["GrossMargin"] = (
    discount_analysis["GrossProfit"] /
    discount_analysis["Revenue"]
)

In [37]:
print(discount_analysis)

  DiscountBand  Orders  UnitsSold      Revenue  GrossProfit  GrossMargin
0           0%     613      28599  750698.6100  351017.3900     0.467588
1         0-5%      87       5194  147905.5250   65688.0600     0.444122
2       10-20%     148       8807  176687.2780   59711.0380     0.337948
3         20%+      72       4349   98938.5675   28887.8625     0.291978
4        5-10%      75       4368   91563.0590   35805.0340     0.391042

## RFM CUSTOMER ANALYSIS

In [38]:
# ==========================================
# RFM CUSTOMER ANALYSIS
# ==========================================

# Reference date = one day after the last order in the dataset
reference_date = profitability["OrderDate"].max() + pd.Timedelta(days=1)

rfm = (
    profitability
    .groupby("CustomerID")
    .agg(
        LastPurchaseDate=("OrderDate", "max"),
        Frequency=("OrderID", "nunique"),
        Monetary=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum")
    )
    .reset_index()
)

# Recency = days since last purchase
rfm["Recency"] = (
    reference_date - rfm["LastPurchaseDate"]
).dt.days

# Reorder columns
rfm = rfm[
    [
        "CustomerID",
        "LastPurchaseDate",
        "Recency",
        "Frequency",
        "Monetary",
        "GrossProfit"
    ]
]

print(rfm.head())

# ==========================================
# RFM SCORING
# ==========================================

rfm["R_Score"] = pd.qcut(
    rfm["Recency"],
    5,
    labels=[5, 4, 3, 2, 1],
    duplicates="drop"
)

rfm["F_Score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
)

rfm["M_Score"] = pd.qcut(
    rfm["Monetary"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
)

rfm["RFM_Score"] = (
    rfm["R_Score"].astype(int).astype(str)
    + rfm["F_Score"].astype(int).astype(str)
    + rfm["M_Score"].astype(int).astype(str)
)

rfm["RFM_Total"] = (
    rfm["R_Score"].astype(int)
    + rfm["F_Score"].astype(int)
    + rfm["M_Score"].astype(int)
)

print(rfm.head())

# ==========================================
# RFM CUSTOMER SEGMENTS
# ==========================================

rfm["RFM_Segment"] = np.select(
    [
        rfm["RFM_Total"] >= 13,
        rfm["RFM_Total"] >= 10,
        rfm["RFM_Total"] >= 7,
        rfm["RFM_Total"] >= 4
    ],
    [
        "Champions",
        "Loyal Customers",
        "Potential Loyalists",
        "At Risk"
    ],
    default="Lost / Low Value"
)

print(
    rfm[
        [
            "CustomerID",
            "Recency",
            "Frequency",
            "Monetary",
            "GrossProfit",
            "RFM_Score",
            "RFM_Total",
            "RFM_Segment"
        ]
    ].head(20)
)

rfm_summary = (
    rfm
    .groupby("RFM_Segment", as_index=False)
    .agg(
        Customers=("CustomerID", "nunique"),
        Revenue=("Monetary", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        AvgRecency=("Recency", "mean"),
        AvgFrequency=("Frequency", "mean"),
        AvgMonetary=("Monetary", "mean")
    )
)

rfm_summary["GrossMargin"] = np.where(
    rfm_summary["Revenue"] != 0,
    rfm_summary["GrossProfit"] / rfm_summary["Revenue"],
    np.nan
)

print(rfm_summary)

  CustomerID LastPurchaseDate  Recency  Frequency    Monetary  GrossProfit
0      ALFKI       1998-04-09       28          6   4273.0000    1974.9000
1      ANATR       1998-03-04       64          4   1402.9500     690.3750
2      ANTON       1998-01-28       99          7   7023.9775    3215.9025
3      AROUT       1998-04-10       27         13  13390.6500    6258.4000
4      BERGS       1998-03-04       64         18  24927.5775   10749.7025
  CustomerID LastPurchaseDate  Recency  Frequency    Monetary  GrossProfit  \
0      ALFKI       1998-04-09       28          6   4273.0000    1974.9000
1      ANATR       1998-03-04       64          4   1402.9500     690.3750
2      ANTON       1998-01-28       99          7   7023.9775    3215.9025
3      AROUT       1998-04-10       27         13  13390.6500    6258.4000
4      BERGS       1998-03-04       64         18  24927.5775   10749.7025

  R_Score F_Score M_Score RFM_Score  RFM_Total
0       3       2       2       322          7
1       2       1       1       211          4
2       1       2       3       123          6
3       3       4       4       344         11
4       2       5       5       255         12
   CustomerID  Recency  Frequency     Monetary  GrossProfit RFM_Score  \
0       ALFKI       28          6    4273.0000    1974.9000       322
1       ANATR       64          4    1402.9500     690.3750       211
2       ANTON       99          7    7023.9775    3215.9025       123
3       AROUT       27         13   13390.6500    6258.4000       344
4       BERGS       64         18   24927.5775   10749.7025       255
5       BLAUS        8          7    3239.8000    1619.9000       522
6       BLONP      115         11   18534.0800    7231.0550       144
7       BOLID       44          3    4232.8500    1461.2000       212
8       BONAP        1         17   21963.2525    9283.2525       555
9       BOTTM       13         14   20801.6000    8587.0250       455
10      BSBEV       23         10    6089.9000    2770.6250       333
11      CACTU        9          6    1814.8000     907.4000       421
12      CENTC      658          1     100.8000      37.8000       111
13      CHOPS       15          8   12348.8800    5680.8300       434
14      COMMI       15          5    3810.7500    1491.9500       412
15      CONSH      104          3    1719.1000     760.8500       111
16      DRACD        3          6    3763.2100    1814.9050       522
17      DUMON       80          4    1615.9000     774.3500       111
18      EASTC        9          8   14761.0350    6742.1600       434
19      ERNSH        2         30  104874.9785   44679.9335       555

    RFM_Total          RFM_Segment
0           7  Potential Loyalists
1           4              At Risk
2           6              At Risk
3          11      Loyal Customers
4          12      Loyal Customers
5           9  Potential Loyalists
6           9  Potential Loyalists
7           5              At Risk
8          15            Champions
9          14            Champions
10          9  Potential Loyalists
11          7  Potential Loyalists
12          3     Lost / Low Value
13         11      Loyal Customers
14          7  Potential Loyalists
15          3     Lost / Low Value
16          9  Potential Loyalists
17          3     Lost / Low Value
18         11      Loyal Customers
19         15            Champions
           RFM_Segment  Customers      Revenue  GrossProfit  AvgRecency  \
0              At Risk         20   74228.9940   33771.8940   78.200000
1            Champions         21  792038.2130  337111.0130    8.857143
2     Lost / Low Value          7    7375.2000    3351.2500  225.285714
3      Loyal Customers         17  243397.7950  103193.3700   28.294118
4  Potential Loyalists         24  148752.8375   63681.8575   36.250000

   AvgFrequency   AvgMonetary  GrossMargin
0      4.750000   3711.449700     0.454969
1     16.523810  37716.105381     0.425625
2      2.571429   1053.600000     0.454394
3     11.176471  14317.517353     0.423970
4      7.500000   6198.034896     0.428105

## Customer Segmentation

In [39]:
revenue_median = customer_profitability["Revenue"].median()
profit_median = customer_profitability["GrossProfit"].median()

customer_profitability["Segment"] = np.select(
    [
        (
            (customer_profitability["Revenue"] >= revenue_median) &
            (customer_profitability["GrossProfit"] >= profit_median)
        ),
        (
            (customer_profitability["Revenue"] >= revenue_median) &
            (customer_profitability["GrossProfit"] < profit_median)
        ),
        (
            (customer_profitability["Revenue"] < revenue_median) &
            (customer_profitability["GrossProfit"] >= profit_median)
        )
    ],
    [
        "High Revenue / High Profit",
        "High Revenue / Low Profit",
        "Low Revenue / High Profit"
    ],
    default="Low Revenue / Low Profit"
)

In [40]:
print(customer_profitability[["Segment"]])

                       Segment
0     Low Revenue / Low Profit
1     Low Revenue / Low Profit
2    Low Revenue / High Profit
3   High Revenue / High Profit
4   High Revenue / High Profit
..                         ...
84  High Revenue / High Profit
85    Low Revenue / Low Profit
86  High Revenue / High Profit
87    Low Revenue / Low Profit
88    Low Revenue / Low Profit

[89 rows x 1 columns]

## Cohort Analysis

In [41]:
first_purchase = (
    orders
    .groupby("CustomerID")["OrderDate"]
    .min()
    .reset_index()
)

first_purchase["CohortMonth"] = (
    first_purchase["OrderDate"]
    .dt.to_period("M")
)

cohort_data = orders.merge(
    first_purchase[
        ["CustomerID", "CohortMonth"]
    ],
    on="CustomerID",
    how="left"
)

cohort_data["OrderMonth"] = (
    cohort_data["OrderDate"]
    .dt.to_period("M")
)

In [42]:
print(cohort_data.head())

   OrderID CustomerID  EmployeeID  OrderDate RequiredDate ShippedDate  \
0    10248      VINET           5 1996-07-04   1996-08-01  1996-07-16
1    10249      TOMSP           6 1996-07-05   1996-08-16  1996-07-10
2    10250      HANAR           4 1996-07-08   1996-08-05  1996-07-12
3    10251      VICTE           3 1996-07-08   1996-08-05  1996-07-15
4    10252      SUPRD           4 1996-07-09   1996-08-06  1996-07-11

   Shipvia  Freight                   ShipName           ShipAddress  \
0        3    32.38  Vins et alcools Chevalier    59 rue de l'Abbaye
1        1    11.61         Toms Spezialitהten         Luisenstr. 48
2        2    65.83              Hanari Carnes       Rua do Paחo, 67
3        1    41.34       Victuailles en stock    2, rue du Commerce
4        2    51.30           Suprךmes dיlices  Boulevard Tirou, 255

         ShipCity ShipRegion ShipPostalCode ShipCountry  OrderYear OrderMonth  \
0           Reims        NaN          51100      France       1996    1996-07
1         Mnster        NaN          44087     Germany       1996    1996-07
2  Rio de Janeiro         RJ      05454-876      Brazil       1996    1996-07
3            Lyon        NaN          69004      France       1996    1996-07
4       Charleroi        NaN         B-6000     Belgium       1996    1996-07

  OrderMonthName OrderMonthDate CohortMonth
0           July        1996-07     1996-07
1           July        1996-07     1996-07
2           July        1996-07     1996-07
3           July        1996-07     1996-07
4           July        1996-07     1996-07

## Revenue Per Customer

In [43]:
revenue_per_customer = (
    profitability.groupby("CustomerID")["Revenue"]
    .sum()
    .mean()
)

print(f"Revenue per Customer: {revenue_per_customer:,.2f}")

Revenue per Customer: 14,222.39

## Monthly Active Customers

In [44]:
profitability["Month"] = profitability["OrderDate"].dt.to_period("M")

monthly_active_customers = (
    profitability.groupby("Month")["CustomerID"]
    .nunique()
    .reset_index(name="Monthly Active Customers")
)

print(monthly_active_customers)

      Month  Monthly Active Customers
0   1996-07                        20
1   1996-08                        18
2   1996-09                        19
3   1996-10                        20
4   1996-11                        21
5   1996-12                        25
6   1997-01                        27
7   1997-02                        21
8   1997-03                        24
9   1997-04                        27
10  1997-05                        26
11  1997-06                        25
12  1997-07                        25
13  1997-08                        30
14  1997-09                        27
15  1997-10                        28
16  1997-11                        27
17  1997-12                        37
18  1998-01                        41
19  1998-02                        35
20  1998-03                        49
21  1998-04                        51
22  1998-05                        13

## Export analytical datasets for the Streamlit dashboard

In [45]:
from pathlib import Path

DASHBOARD_DATA_DIR = Path(r"C:\Users\User\Desktop\ספיר\אישי\קורס דאטה אנליסט אנליזה\Northwind project\dashboard_data")
DASHBOARD_DATA_DIR.mkdir(parents=True, exist_ok=True)

tables = {
    "profitability": profitability,
    "product_profitability": product_profitability,
    "category_profitability": category_profitability,
    "customer_profitability": customer_profitability,
    "volume_margin": volume_margin,
    "employee_profitability": employee_profitability,
    "country_profitability": country_profitability,
    "monthly_profitability": monthly_profitability,
    "discount_analysis": discount_analysis,
    "monthly_active_customers": monthly_active_customers,
    "rfm": rfm,
    "rfm_summary": rfm_summary,
}

for name, table in tables.items():
    table.to_csv(DASHBOARD_DATA_DIR / f"{name}.csv", index=False)

print("Exported to:", DASHBOARD_DATA_DIR)
print("Files:", list(tables.keys()))

Exported to: C:\Users\User\Desktop\ספיר\אישי\קורס דאטה אנליסט אנליזה\Northwind project\dashboard_data
Files: ['profitability', 'product_profitability', 'category_profitability', 'customer_profitability', 'volume_margin', 'employee_profitability', 'country_profitability', 'monthly_profitability', 'discount_analysis', 'monthly_active_customers', 'rfm', 'rfm_summary']